# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
name: Build

on:
  push:
    branches: [ "*" ]
env:
  SCCACHE_GHA_ENABLED: "true"
  SWIFTC_WRAPPER: sccache  
  SCCACHE_LOG: debug
  SCCACHE_NO_DAEMON: 1
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Run sccache-cache
      uses: mozilla-actions/sccache-action@v0.0.3
      
    - name: Cache Swift PM dependencies
      uses: actions/cache@v4
      with:
        path: |
          ./Swiftness/.swiftpm/
          ./Swiftness/.build/
        key: ${{ runner.os }}-swift-${{ hashFiles('Swiftness/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swift-${{ hashFiles('Swiftness/Package.resolved') }}
          ${{ runner.os }}-swift
          
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      
    - name: Check Swift Version
      run: swift --version
      
    - name: Build
      working-directory: ./Swiftness/
      run: |
        sccache --zero-stats
        swift build -v -c release
        sccache --show-stats
    
