# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
name: Build

on:
  push:
    branches: [ "*" ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
        
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2      
    
    - name: Restore timestamps
      uses: chetan/git-restore-mtime-action@v2
    
    - name: Cache Swift PM
      uses: actions/cache@v4
      with:
        path: |
          ./Swiftness/.build
          ./Swiftness/.swiftpm
          ./Swiftness/.build/plugins 
          ./Swiftness/.build/artifacts
          ~/.swiftpm
        key: ${{ runner.os }}-swiftness-${{ hashFiles('Swiftness/Package.resolved', '**/openapi.yaml') }}
        restore-keys: |
          ${{ runner.os }}-swiftness-${{ hashFiles('Swiftness/Package.resolved', '**/openapi.yaml') }}
      
    - name: Check Swift Version
      run: swift --version
    
    - name: Build Project
      working-directory: ./Swiftness/
      run: |
        swift build -c release
