# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift
name: Build

on:
  push:
    branches: [ "*" ]
env:
  SCCACHE_GHA_ENABLED: "false"
  SCCACHE_DIR: ${{ github.workspace }}/.sccache
  SWIFTC_WRAPPER: sccache  
  SCCACHE_LOG: debug
  SCCACHE_NO_DAEMON: 1
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Install sccache
      run: |
        SCCACHE_VERSION=v0.8.2
        curl -L "https://github.com/mozilla/sccache/releases/download/$SCCACHE_VERSION/sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl.tar.gz" | tar xz
        sudo mv sccache-$SCCACHE_VERSION-x86_64-unknown-linux-musl/sccache /usr/local/bin/
        chmod +x /usr/local/bin/sccache
    
    # - name: Run sccache-cache
    #   uses: mozilla-actions/sccache-action@v0.0.3
      
    - name: Cache Swift PM dependencies
      uses: actions/cache@v4
      with:
        path: |
          ./Swiftness/.swiftpm/
          ./Swiftness/.build/
          ${{ github.workspace }}/.sccache
        key: ${{ runner.os }}-swift-${{ hashFiles('Swiftness/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swift-${{ hashFiles('Swiftness/Package.resolved') }}
          ${{ runner.os }}-swift
          
    - name: Setup Swift
      uses: swift-actions/setup-swift@v2
      
    - name: Check Swift Version
      run: swift --version
      
    - name: Build
      working-directory: ./Swiftness/
      run: |
        sccache --start-server
        sccache --zero-stats
        swift build -v -c release
        sccache --show-stats
        sccache --stop-server
    
